name: Release sui AMD64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          cache: false
          go-version: ~1.25.10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
          cd ..

          rm -rf backend/web/html
          mv frontend/dist backend/web/html

      - name: Build sui
        env:
          CGO_ENABLED: "1"
          GOOS: linux
          GOARCH: amd64
        run: |
          cd backend

          go build \
            -trimpath \
            -ldflags "-s -w -buildid=" \
            -o ../sui \
            main.go

          cd ..
          chmod +x sui

      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: "0.0.1"
          file: sui
          asset_name: sui-linux-amd64
          prerelease: true
          overwrite: true
